export const yogaPageContent = {
  homeCta: 'Quiero comenzar yoga',
  eyebrow: 'Un toque de Luz · Yoga',
  title: 'Un espacio para volver a tu cuerpo.',
  introduction: 'Practicamos yoga en grupo, con tiempo para respirar, movernos y encontrar un ritmo propio. No necesitás experiencia previa.',
  primaryActionRegister: 'Registrarme para reservar',
  primaryActionBooking: 'Reservar clase',
  whatsappLabel: '¿Tenés dudas? Consultanos por WhatsApp',
  whatsappMessage: 'Hola, tengo dudas sobre las clases de Yoga.',
  backHome: 'Volver al inicio',
  aboutEyebrow: 'La práctica',
  aboutTitle: 'Yoga para habitar el presente',
  aboutBody: 'Cada encuentro combina movimiento consciente, respiración y relajación. La propuesta acompaña distintos ritmos y busca que puedas construir una práctica amable y sostenida.',
  howTitle: 'Cómo funcionan los ciclos',
  howSteps: [
    { title: 'Elegís tus horarios', body: 'Cada ciclo reúne clases semanales en días y horarios definidos.' },
    { title: 'Reservás tu lugar', body: 'Creás tu cuenta y seleccionás el ciclo que mejor se adapta a tu semana.' },
    { title: 'Practicás en grupo', body: 'Tu reserva queda asociada a las clases futuras de los horarios elegidos.' },
  ],
  cyclesEyebrow: 'Próximas prácticas',
  cyclesTitle: 'Ciclos vigentes',
  cyclesLoading: 'Cargando ciclos…',
  cyclesError: 'No pudimos cargar los ciclos en este momento. Probá nuevamente más tarde.',
  cyclesEmpty: 'Pronto abriremos nuevos ciclos',
  cyclesEmptyDetail: 'Estamos preparando los próximos horarios de práctica.',
  cycleDates: 'Del {start} al {end}',
  classesPerWeek: '{count} clases por semana',
  scheduleLabel: 'Días y horarios',
  available: 'Con lugares disponibles',
  full: 'Sin lugares disponibles',
  duration: '{minutes} min',
  cycleAction: 'Elegir este ciclo',
  bookingPrompt: 'Los ciclos se reservan desde tu cuenta.',
  loadingLabel: 'Ciclos de Yoga',
  cyclesErrorLabel: 'Error al cargar los ciclos',
  schedulesLabel: 'Horarios del ciclo',
}
